country_code = ""

[logging]
level = ""
file_path = ""

[api]
dodo_api_url = ""
database_api_url = ""
auth_api_url = ""

[partial_ingredient_stop_sales]
disallowed_ingredient_names = []
allowed_ingredient_names = []

[cheated_orders]
skipped_phone_numbers = [
    ""
]

[message_queue]
rabbitmq_url = ""
